version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: supershop-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vivianstore_db
      MYSQL_USER: cheseh2005
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: supershop-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: vivianstore_db
      DB_USER: cheseh2005
      DB_PASSWORD: yourpassword
    depends_on:
      - mysql
