services:
  mysql:
    image: mysql:8.1
    container_name: supershop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: vivianstore_db
      MYSQL_USER: cheseh2005
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: supershop-app
    container_name: supershop-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vivianstore_db
      SPRING_DATASOURCE_USERNAME: cheseh2005
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql

volumes:
  db-data:
